### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by ghost** [ArtisanBurger/prj-rev-bwfs-dasmoto#3]
Comments are necessary to provide information about code to readers. Add more comments throughout your code.

https://github.com/ArtisanBurger/prj-rev-bwfs-dasmoto/blob/9e9811304442a0cba64dc81e9e8e079195b1c27d/DasmotoArtsAndCrafts/index.html#L21

**Comment by ArtisanBurger** [comment]
I appreciate the feedback. I'm normally better about commenting but I was so focused on getting the project done that I totally forgot to comment as I progressed. Thanks for the reminder!!
